export const APP_CONSTANTS = {
  // Telegram Bot Constants
  TELEGRAM_CHATS_PER_PAGE: 6,
  TELEGRAM_MAX_MESSAGE_LENGTH: 4000,
  TELEGRAM_CHUNK_SAFE_LENGTH: 3800,

  // Summarization & Formatting Constants
  MAX_TRANSCRIPT_CHARACTERS: 60000,
  DEFAULT_SUMMARY_MESSAGE_LIMIT: 100,
  MIN_SUMMARY_MESSAGE_LIMIT: 5,
  MAX_SUMMARY_MESSAGE_LIMIT: 500,
  PREVIOUS_CONTEXT_MESSAGE_COUNT: 5,

  // API Pagination Constants
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_API_LIMIT: 100,

  // Concurrency & Performance
  CONTACT_BATCH_CONCURRENCY: 10,

  // Process & Lifecycle
  SHUTDOWN_TIMEOUT_MS: 10000,
} as const;
